### ISSUE TITLE
Update the Material Suggestion for PD5 parts

### ISSUE THREAD

**Issue by Eaton-James** [Eaton-Corp/Lightning-Pro#24]
If LPRO identifies a PD%5#* part number, take the first 6 characters. Null this replacement.
If LPRO identifies a PD%5X* part number, take the whole string. Null this replacement.

Concatenate the above to make a new part number: PD%5#%_PD%55X*******. Use this for the Find/Replace.

See James for more details.

**Comment by Virdir2** [comment]
PD5 breaker concatenation implemented post LP v2.9.11.
