### ISSUE TITLE
QR Codes on Assembler screen are too small

### ISSUE THREAD

**Issue by Eaton-James** [Eaton-Corp/Lightning-Pro#46]
Can we make the QR codes bigger? or have a button to pop-up another window with larger QR codes?

Second option may make it easier to include more codes in the future.

**Comment by Eaton-James** [comment]
I think a pop-up solution would be better because we need the GO-Item to also include the "B" item suffix.

**Comment by Virdir2** [comment]
Assembler screen QRviewer feature implemented post 2.9.11. Will have future capacity to display as many QR codes necessary for the GO as well.
