### ISSUE TITLE
Add Search ALL in the the Search By options

### ISSUE THREAD

**Issue by Eaton-James** [Eaton-Corp/Lightning-Pro#50]
Add Search ALL in the the Search By options

**Comment by Eaton-James** [comment]
Default the Search By to ALL

**Comment by Virdir2** [comment]
![image](https://github.com/Eaton-Corp/Lightning-Pro/assets/121146599/6e5e663e-d164-4084-b215-3785b0aaf088)

**Comment by Virdir2** [comment]
Search By All (default) will query for all possible field options (ShopOrder is 6 fields).
