### ISSUE TITLE
Add Filters to the Material List view for the Assemblers

### ISSUE THREAD

**Issue by Eaton-James** [Eaton-Corp/Lightning-Pro#52]
Push first

**Comment by Eaton-James** [comment]
Add a filter to search  by Part Number or Message. Also add a toggle to view all line items or the selected line item.

**Comment by Eaton-James** [comment]
Add a dropdown to view only B lines or I lines

**Comment by Virdir2** [comment]
![image](https://github.com/Eaton-Corp/Lightning-Pro/assets/121146599/c436d1ac-7f38-4af5-a259-6fb69d985e45)

**Comment by Virdir2** [comment]
Search ability added to Material on Assembler page. 

Search Preference:
Allows the users to differentiate between Contains or Equals search.

Search By:
Allows the users to query the Part Number, Shortage Message, or both.

Search For I/B/T:
Allows the users to filter for only Interior, Box, or Trim GO Items. All (default) will show everything - even GO Items not ending in I, B, or T. 

LineItem Only Check:
The currently selected GO Item will always have its rows highlighted in GREEN. When LineItem only is toggled to true then the user will only see these rows. When LineItem only is off the user will see all GO Items relating to the GO.
