### ISSUE TITLE
LPRO Creates a new folder when 1 already exists

### ISSUE THREAD

**Issue by Eaton-James** [Eaton-Corp/Lightning-Pro#59]
LPRO Creates a new folder when 1 already exists. It should search within the folder name if it contains that GO and use that folder instead of creating a new one.

**Comment by Virdir2** [comment]
![image](https://github.com/Eaton-Corp/Lightning-Pro/assets/121146599/57ad1874-5b0b-4748-8e3a-26f6259b6992)

**Comment by Virdir2** [comment]
Flow for correct order files folder handled. If there are multiple folder options the user will be prompted to select their folder of choice or to default to the standard 10 digit GO folder.
