### ISSUE TITLE
Promotion/Demotion be moved 1 bucket at a time

### ISSUE THREAD

**Issue by Eaton-James** [Eaton-Corp/Lightning-Pro#62]
In current state, depending on the role, the promotion and demotion can skip based on the Role selected.

Can it just move 1 bucket at a time and be limited by the Role?

**Comment by Virdir2** [comment]
Specialist and Supervisor roles updated to move 1 bucket only promotion and demotion within the range of InDevelopment through to Production inclusive. 

Assemblers can only demote and these jobs are sent back to the Supervisor (MI Complete).
