### ISSUE TITLE
Add Catalog Number onto the Rating Label

### ISSUE THREAD

**Issue by Eaton-James** [Eaton-Corp/Lightning-Pro#72]
Add Catalog Number onto the Rating Label

**Comment by Virdir2** [comment]
Adjust the Catalog Number on to the assembler/production display as well.

**Comment by Virdir2** [comment]
![image](https://github.com/user-attachments/assets/239f080e-e188-47c0-bf17-0759185530db)

**Comment by Virdir2** [comment]
Build product ID added to labels.
