### ISSUE TITLE
Change code from PSC to an XML parameter to determine Product Group

### ISSUE THREAD

**Issue by Eaton-James** [Eaton-Corp/Lightning-Pro#73]
We are seeing an issue with the PSC choosing the correct product group/product area. Sometimes the wrong product group is being selected which causes an issue.

Suggesting to change the code to move away from the PSC and use a parameter in the XML to determine the product group instead.

**Comment by Virdir2** [comment]
Marketing team to have more specific PSC starting August 15th. Take the back seat on this fix and see if it can be resolved with a simpler solution afterwards.
