### ISSUE TITLE
Add the ability to use webcam to scan barcodes

### ISSUE THREAD

**Issue by abdullahEaton** [Eaton-Corp/Lightning-Pro#78]
Winnipeg and Dartmouth want to use tablets. 

On the assembler page we want to be able to live scan with the camera of the tablet instead of the barcode scanner

On click of the assembler page:
- open camera
- scan barcode 
- returns to assembler page with job loaded

**Comment by Virdir2** [comment]
Assembler page now has the functionality to open up the computer cam and use it to cam scan for barcodes. Will work for LP QR codes / barcodes and discrete barcodes as well.
